## Server Properties
server:
  port: 8083
  compression:
    enabled: true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  application: 
    name: trx-service 
  datasource: 
#    url: jdbc:postgresql://localhost:5432/TestLoginMandiUang
    url: jdbc:postgresql://localhost:5432/TestAutoDDL2
    username: postgres
    password: admin
    initialization-mode: always
  jackson:
    time-zone: GMT+7
    serialization:
      write-dates-as-timestamps: false        

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

##Eureka Properties
eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost

## App Properties
app: 
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
    

